### ISSUE TITLE
Homework Feedback Node.js Week 2

### ISSUE THREAD

**Issue by r0hitsharma** [berheg/hyf-homework#2]
Works well, but I think you're relying too much on examples without understanding what all the things do. I would recommend you to go through your code and remove things you don't quite understand, see if it breaks things, and if so, if you can replace them yourself. Ask if you get stuck!

https://github.com/berheg/hyf-homework/blob/5c653c5e1c837ad0440fa23733aee740d3b02ed7/nodejs/week2/warmup/index.js#L10

It's a good idea to give feedback to user when parameters are not present, but it would be better to do it within the request handler of this function (i.e. line 22). That way you're not limited to just checking URL, but can check if `first` and `second` both are present, and if they are numbers etc. (I see you have implemented some of it, it's better to keep all that code close).

https://github.com/berheg/hyf-homework/blob/5c653c5e1c837ad0440fa23733aee740d3b02ed7/nodejs/week2/mealSharing/package.json#L7

You should implement NPM scripts to run your app properly. The user might not know what to do exactly.

https://github.com/berheg/hyf-homework/blob/5c653c5e1c837ad0440fa23733aee740d3b02ed7/nodejs/week2/mealSharing/src/backend/index.js#L6

This pattern for imports (require) should be avoided if unnecessary. 

https://github.com/berheg/hyf-homework/blob/5c653c5e1c837ad0440fa23733aee740d3b02ed7/nodejs/week2/mealSharing/src/backend/index.js#L4

Why are you using `bodyParser` middleware here?

**Comment by berheg** [comment]
Thank you for feedback will make corrections accordingly.
